POST http://localhost:3001/api/blogs/5cf1d4a61bda9e2908dc6365/comments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMTAiLCJpZCI6IjVjZTgzODQxY2JiMDBkNDg4MDZmNjhkOSIsImlhdCI6MTU1ODcyMjY0MH0.JkHpNYWAb_MTEyE7ifkqVKZn2PeNPCrRMmY8lNUUack

{
   "text": "Hei vaan uusi malli"
}